name: Cleanup base images

on:
  schedule:
    - cron: "0 3 2,16 * *" # every 2nd and 16th of the month at 3am UTC

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Cleanup old images
        uses: SmartsquareGmbH/delete-old-packages@v0.7.0
        with:
          type: container
          names: |
            base_cuda_main
            base_cuda_pr
            base_cuda_singularity_main
            base_cuda_singularity_pr
            base_hip_main
            base_hip_pr
            base_openmp_main
            base_openmp_pr
            base_sycl_main
            base_sycl_pr
